---
- name: Update
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add an apt signing key for Docker
  ansible.builtin.apt_key:
    id: 8D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Get package architecture
  register: dpkg_architecture
  command: dpkg --print-architecture

- name: Add apt repository for stable version
  block:
    - name: docker | apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Regenerate containerd configuration
  shell: |
      containerd config default > config.toml;
      sed -E 's/\s+SystemdCgroup=/SystemdCgroup=true/g' config.toml;
      sudo mv -f config.toml /etc/containerd/
  
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Get user
  become: false
  command: whoami
  register: whoami

- name: Set up user on sudoers
  shell: |
    cat<<EOF | sudo tee /etc/sudoers.d/{{whoami.stdout}}
    {{whoami.stdout}} ALL=(ALL) NOPASSWD:ALL
    EOF

- name: Install utilities
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - vim
    - jq

